FROM openjdk:17

MAINTAINER "Nageswara"


ADD target/spring-boot-docker-welcome-app.jar  spring-boot-docker-welcome-app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "spring-boot-docker-welcome-app.jar"]